### ISSUE TITLE
一个可能导致重复开启的bug？

### ISSUE THREAD

**Issue by RedFog** [connection-lost/ZjsnViewer#11]
从使用支持2.0.0版本的viewer以后，在有些时候游戏内贴图会失败(变成黑色图块)，并且退出游戏时会重新进入登录页面。以前认为这是该游戏众多bug之一，但是后来有一次我在使用viewer的提醒进入了游戏收了远征之后，点击战舰少女R应用的图标进入游戏后立刻出现了这种情况。因此我猜想是否是viewer和应用打开的游戏存在着一些不同，或者说导致了游戏重复打开？
希望您能够发现问题并解决，谢谢(๑•̀ㅂ•́)و✧

**Comment by JohnnySun** [comment]
这个问题的确是有遇到过，作者最近好像没有上线，个人感觉应该是因为应用通过cocos2d重写后导致的，但是为什么会出现这个问题我也没有研究过，回头看看吧
