### ISSUE TITLE
是不是幻萌的包名称又改了？

### ISSUE THREAD

**Issue by fatcabbage** [connection-lost/ZjsnViewer#13]
貌似又开启了莫名其妙的账号已在他处登陆。。。
烦请查一下是不是包名称又从com.xxx变成其他的了

**Comment by youngpen** [comment]
现在的包名是com.huanmeng.zhanjian2

**Comment by fatcabbage** [comment]
就是下了这边改过包名称为com.huanmeng.zhanjian2的版本，前段（从这边放出到大概2.26/27）一直好的，最近1-2天又不能正常检测到前台进程出现顶号了，才问的。。。
