### ISSUE TITLE
关于新版战舰少女R适配

### ISSUE THREAD

**Issue by JohnnySun** [connection-lost/ZjsnViewer#4]
刚刚抓了下包，也看了下你的代码.
通过抓包发现，现在hm把login服务器改为了http://login.jianniang.com/index/passportLogin/

登录服务器也变为
_public static String[] url_server_hm = {
            "http://zj.alpha.jianniang.com/",
            "http://s2.jianniang.com/",
            "http://s3.jianniang.com/",
            "http://s4.jianniang.com/",
            "http://s5.jianniang.com/",
            "http://s6.jianniang.com/",
            "http://s7.jianniang.com/",
            "http://s8.jianniang.com/",
            "http://s9.jianniang.com/",
            "http://s10.jianniang.com/",
            "http://s11.jianniang.com/"
    };_
登录的流程也跟以前没有太大的差别，还是先
1. passportLogin/username/password
2. index/uid
3. 4412    265.598350000   192.168.31.200  180.97.163.7    HTTP    478 GET /api/initGame/&t=1447678445744&e=15ef8c34b1d475ebfef67e3fbf2c37ab&gz=1&market=2&channel=0&version=2.0.0 HTTP/1.1 

第三步的api和以前貌似有些不同，我看你代码里以前抓出来的api是api/initGame&t=233&e=5f3cd4e0d30c4376f8c9685d263f5184

logcat你的app发现在me.crafter.android.zjsnviewer W/System.err:     at me.crafter.android.zjsnviewer.NetworkManager.updateDockInfo(NetworkManager.java:175)这里抛了异常
-  in = new BufferedReader(new InputStreamReader(connection.getInputStream()));*

怀疑此异常是hm吧非正常的get请求返回了404所致。

暂时还没想好解决方法，不知您怎么想

**Comment by connection-lost** [comment]
这里是一段加密信息: &e=5f3cd4e0d30c4376f8c9685d263f5184
加密信息&e=的生成方法是： （"请求链接"+"&t="+"当前Unix时间（以前是.net时间）"+"一段固定字符SecretKey" ）的md5
现在怀疑hm打开了时间验证，只有当前时间和服务器差不多才可以请求成功（游戏打开的时候会请求时间，所以无视了手机时间），以前用233也就是因为没有时间验证我瞎写的。
现在，比较好的情况是，加密方式没有改，我需要解包获得那段SecretKey，最差的情况是加密方式也改了，但是&e这段文字看起来仍然像md5

总结，需要SecretKey

**Comment by JohnnySun** [comment]
&e这段我感觉也是md5

**Comment by JohnnySun** [comment]
但是我还是有一点我很好奇，以前的&e看起来你也是用了固定的，如果他要是做时间验证的话，&e里肯定已经有一个unix时间了，他还要去实现一个可能是md5加密过的&t，这样有一个问题，他如果是md5的话，他服务器那边应该也是无法解密的，用来做时间验证感觉并不是那么可能性大，毕竟他们连密码现在都是明文。。 回头还是解包下他们的app在看下吧

**Comment by JohnnySun** [comment]
@connection-lost 时间验证这边倒是有解决方法，抓包显示&t= 后面应当接当前的unixtime，那现在&e这边应该也是md5不会变， 也就是只要解包找到SecretKey就可以了。 那就是跟你上面的回复是一样的了，找到SecretKey，按照md5("请求链接"+"&t="+"当前Unix时间（以前是.net时间）"+"一段固定字符SecretKey" )的方式得到正确的&e应该就可以用了

**Comment by JohnnySun** [comment]
@connection-lost 能否开一个工作分支，用来提交hm服2.0版本的测试用代码

**Comment by JohnnySun** [comment]
晚上抽了下时间对他解包看了下，倒是已经实装coscos2d了，但是能力有限，并没有能够找到SecretKey :(

**Comment by JohnnySun** [comment]
仅仅在拆包里找到了一对RSA密钥
`public static final String RSA_PRIVATE = "MIICXQIBAAKBgQDYdjZJPvaXfScJL1FeDPpjmPX0do5ZJzM4ZnYbRer4sowaiOutYVex23NySpyUpF6Pu5ljgaBnWVNtl9LbRDJTpexoYCHzHjCW4T7KN0mKgX67RZSvRnKRZGciRBS6X+McT4DqKyUVIwie3q9eAPZh/cITgKJHOuOW/8n+KERm2wIDAQABAoGAftnXuljhnalEJQfLwTgNzCwphterV+e3BohVEmqI5rGLlUlEA9kV0S7vmrzKwfkJSWYA3+VpIOeiEol0kfaHHpYn27vWU3FWvovvkA1CpX0Zy84KKxRiuA0oJaXrTevgLU46RWJOUZbUJ8g3bWHRwNh7NoWvpOZVPIxFgjvbXjECQQDsCndlXuyBFnOWvYeP76fWaf8Eb7cmtjoHs0z+0IHCOcYtBe52Yrp/+lEAfarLJSyQTde1gsgfmnusIT2nVTpnAkEA6sPritvhTT8la2RznSlQjzk0IVKpSudU5YvjJeDdSfecFMCFiLb4SN8lwHGt7DidYhGaL6BP/n053zlCZO2PbQJATvDZKX/rnOiDU+CjG9JM0Xq1nSg3mqzLD5Q5pebZ3rkvvBMFw3YVZYOz33Qn0LToCILgJ4ZLo7YoslKTqgjo9QJBAOWeIu96CG9pZ8wWQA5jrmunY5mEJBkjEiJCJDWULlx+VqbldrY1X7rGp0IG7jmxVh3pYYlbn2ImUUhH1OyqfjECQQDWVm2l2wNwTyb8zPTkDdEKBRAHCqt2KDSJCalCrKlUpVa+860WFMzhXfPWd7w21H7Y5eZJy5sXVNCNRH56yDzY";`

`public static final String RSA_PUBLIC = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYdjZJPvaXfScJL1FeDPpjmPX0do5ZJzM4ZnYbRer4sowaiOutYVex23NySpyUpF6Pu5ljgaBnWVNtl9LbRDJTpexoYCHzHjCW4T7KN0mKgX67RZSvRnKRZGciRBS6X+McT4DqKyUVIwie3q9eAPZh/cITgKJHOuOW/8n+KERm2wIDAQAB";`

使用方法如下：

```
`public static String sign(String paramString){
return SignUtils.sign(paramString, "MIICXQIBAAKBgQDYdjZJPvaXfScJL1FeDPpjmPX0do5ZJzM4ZnYbRer4sowaiOutYVex23NySpyUpF6Pu5ljgaBnWVNtl9LbRDJTpexoYCHzHjCW4T7KN0mKgX67RZSvRnKRZGciRBS6X+McT4DqKyUVIwie3q9eAPZh/cITgKJHOuOW/8n+KERm2wIDAQABAoGAftnXuljhnalEJQfLwTgNzCwphterV+e3BohVEmqI5rGLlUlEA9kV0S7vmrzKwfkJSWYA3+VpIOeiEol0kfaHHpYn27vWU3FWvovvkA1CpX0Zy84KKxRiuA0oJaXrTevgLU46RWJOUZbUJ8g3bWHRwNh7NoWvpOZVPIxFgjvbXjECQQDsCndlXuyBFnOWvYeP76fWaf8Eb7cmtjoHs0z+0IHCOcYtBe52Yrp/+lEAfarLJSyQTde1gsgfmnusIT2nVTpnAkEA6sPritvhTT8la2RznSlQjzk0IVKpSudU5YvjJeDdSfecFMCFiLb4SN8lwHGt7DidYhGaL6BP/n053zlCZO2PbQJATvDZKX/rnOiDU+CjG9JM0Xq1nSg3mqzLD5Q5pebZ3rkvvBMFw3YVZYOz33Qn0LToCILgJ4ZLo7YoslKTqgjo9QJBAOWeIu96CG9pZ8wWQA5jrmunY5mEJBkjEiJCJDWULlx+VqbldrY1X7rGp0IG7jmxVh3pYYlbn2ImUUhH1OyqfjECQQDWVm2l2wNwTyb8zPTkDdEKBRAHCqt2KDSJCalCrKlUpVa+860WFMzhXfPWd7w21H7Y5eZJy5sXVNCNRH56yDzY"); }`
```

sign原型：

```
 `public static String sign(String paramString1, String paramString2)  {
try
{
  paramString2 = new PKCS8EncodedKeySpec(Base64.decode(paramString2));
  paramString2 = KeyFactory.getInstance("RSA").generatePrivate(paramString2);
  Signature localSignature = Signature.getInstance("SHA1WithRSA");
  localSignature.initSign(paramString2);
  localSignature.update(paramString1.getBytes("UTF-8"));
  paramString1 = Base64.encode(localSignature.sign());
  return paramString1;
}`
```

但感觉这个好像是用来做支付验证的，但除此之外也并没有找到其他的Key，所以有没有可能&c是 url通过rsa加密后的base64的md5呢？

**Comment by connection-lost** [comment]
支付的模块仍然在classes.dex里面，但是游戏实际内容应该全在lib/armeabi/libcocos2djs.so中。目前已经确认该游戏并没有混淆变量名，但是通过解包并没有发现一个叫SecretKey的变量。如果能dump下所有的variable（带名字）也许可以有头绪。

**Comment by connection-lost** [comment]
但是话说回来，这个包我不是很会解，所以可能需要找其他知道怎么解cocos2d的人帮忙了

**Comment by JohnnySun** [comment]
等北京时间明天我在研究下吧，coscos2d我也不是很清楚

**Comment by JohnnySun** [comment]
想了下，so文件应该是c/c++写出来的，如果这种so和linux下的动态链接库一样的话，那应该也只有ida能够反编译了

**Comment by connection-lost** [comment]
有神秘人解决了这个问题
see pull request#4
